### ISSUE TITLE
packageFiles

### ISSUE THREAD

**Issue by noraj** [renovatebot/docs.renovatebot.com#5]
In two pages there are a mention of `packageFiles`:

- https://docs.renovatebot.com/configuration-options/
- https://docs.renovatebot.com/faq/

But this option isn't documented anywhere. Is it an old option that no longer exists? Or is it now `packageRules` or `packageNames`?

**Comment by rarkins** [comment]
You are right, it's a long-removed legacy option. I'll remove it from the docs too. Thanks
