### ISSUE TITLE
Switch to Docusaurus

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docs.renovatebot.com#9]
Supercedes https://github.com/renovatebot/renovate/issues/6944

**Comment by HonkingGoose** [comment]
I'm confused, why do we have `renovatebot/docs.renovatebot.com` **and** `renovatebot/renovatebot.github.io`?
Are you intending for one of those repositories to get archived once we've migrated to Docusaurus v2?

**Comment by rarkins** [comment]
Actually this is the old one and I need to archive it so that I don't mix them up again
